api:
   dashboard: true
   insecure: true
log:
  level: DEBUG
entryPoints:
  web:
    address: ":80"
  csi-tcp:
    address: ":9100"
  postgres-tcp:
    address: ":5432"

  websecure:
    address: ":443"
    transport:
      respondingTimeouts:
        readTimeout: "0s"
certificatesResolvers:
  letsencrypt:
    acme:
      storage: /etc/traefik/acme/acme.json
      email: admin@io12.me
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 0

providers:
  nomad:
    watch: true
    endpoint:
      address: http://192.168.40.120:4646
      {{with secret "providers/data/nomad_observer"}}
      token: {{.Data.data.token}}
      {{end}}
  file:
    filename: /local/config.yaml