on:
  push:
    branches:
    - main
jobs:
  deploy_nomad:
    strategy:
      matrix:
        include:
          - dir: jobs/traefik
            file: traefik.hcl
    name: Deploy to lab
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: lucasmelin/setup-nomad@v1
      - name: Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:homelab
      - name: Deploy app
        working-directory: ${{ matrix.dir }}
        env:
          NOMAD_TOKEN: ${{ secrets.NOMAD_TOKEN }}
        run:
          nomad job run -address http://192.168.40.120:4646 traefik.hcl