name: Homelab deploy

on:
  workflow_dispatch:
    inputs:
      all:
        description: deploy all services
        required: false
        type: boolean
  push:
    branches:
    - main
    
jobs:
  deploy_nomad:
    strategy:
      fail-fast: false
      matrix:
        include:
          - dir: jobs/traefik
            file: traefik.hcl
          - dir: jobs/cloudflared
            file: cloudflared.hcl
          - dir: jobs/blinko
            file: blinko.hcl
          # - dir: jobs/postgres
          #   file: postgres.hcl
          - dir: jobs/gitea
            file: gitea.hcl
          - dir: jobs/paperless
            file: paperless.hcl
          - dir: jobs/redis
            file: redis.hcl
#          - dir: jobs/storage-controller
#            file: storage-controller.hcl
#          - dir: jobs/storage-node
#            file: storage-node.hcl
    name: Deploy to lab
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            changed:
              - './${{ matrix.dir }}/**'
      - uses: lucasmelin/setup-nomad@v1
        if: steps.filter.outputs.changed == 'true' || inputs.all
      - name: Tailscale
        if: steps.filter.outputs.changed == 'true' || inputs.all
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:homelab
      - name: Deploy app
        if: steps.filter.outputs.changed == 'true' || inputs.all
        working-directory: ./${{ matrix.dir }}
        env:
          NOMAD_TOKEN: ${{ secrets.NOMAD_TOKEN }}
        run:
          nomad job run -address http://192.168.40.120:4646 ${{ matrix.file }}